// Parser
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>

/* Character classes */
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

/* Token codes */
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26

void addChar();
void getChar();
void getNonBlank();
int lex();

void factor();
void term();
void expr();

void factor() {
  printf("Enter <factor>\n", );

  if (nextToken == IDENT || nextToken == INT_LIT) {
    // Get the next token
    lex();
  } else {
    if (nextToken == LEFT_PAREN) {
      lex();
      expr();
      if (nextToken == RIGHT_PAREN) {
        lex();
      } else {
        error();
      }
    } else {
      error();
    }
  }
  printf("Exit <factor>\n", );
}

/* term
   Parses strings in the language generated by the rule:
   <term> -> <factor> {(* | /) <factor>)
*/
void term() {
  printf("Enter <term>\n");

  /* Parse the first factor */
  factor();

  /* As long as the next token is * or /, get the
    next token and parse the next factor
   */

  while nextToken == MULTI_OP || nextToken == DIV_OP) {
    lex();
    factor();
  }
  printf("Exit <term>\n", );
} /* End of function term */

/* expr
  Parses strings in the language generated by the rule:
  <expr> -> <term> {(+ | -) <term>}
*/

void expr() {
  printf("Enter <expr>\n");

  /* Parse the first term */
  term();

  /* As long as the next token is + or -, get
    the next token and parse the next term */
  while (nextToken == ADD_OP || nextToken == SUB_OP) {
     lex();
     term();
  }

  printf("Exit <expr>\n");

} /* End of function expr */

int main() {
  FILE *f;
  char c;
  f = fopen("input.txt", "rt");

  fclose(f);
  return 0;
}
